exclude:
  - data-pull/
  - package.json
  - package-lock.json
  - README.md
  - assets/maps/*.json
  - assets/data/*.json
  - assets/js/display/
  - assets/js/map.js
  - assets/js/tables.js
  - assets/js/search.js
