name: Minify Site JS
on:
  push:
    branches:
      - master

jobs:
  minify-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'assets/js'
          js_engine: uglify-js
      - name: Auto Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b minified
          git add .
          git commit -m "Github Actions: Minified JS"
          git push -f origin minified
